version: '3.2'

services:
  service-account:
    build:
      context: .
      dockerfile: apps/service-account/Dockerfile
      args:
        NODE_ENV: development
    image: 'service-account:latest'
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50054:50054
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: 'gitlabregcrednew'
      kompose.image-pull-policy: 'Always'

  service-access:
    build:
      context: .
      dockerfile: apps/service-access/Dockerfile
      args:
        NODE_ENV: development
    image: 'service-access:latest'
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50089:50089
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: 'gitlabregcrednew'
      kompose.image-pull-policy: 'Always'

  service-billing:
    build:
      context: .
      dockerfile: apps/service-billing/Dockerfile
      args:
        NODE_ENV: development
    image: 'service-billing:latest'
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50067:50067
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: 'gitlabregcrednew'
      kompose.image-pull-policy: 'Always'

  service-notification:
    build:
      context: .
      dockerfile: apps/service-notification/Dockerfile
      args:
        NODE_ENV: development
    image: 'service-notification:latest'
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50044:50044
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: 'gitlabregcrednew'
      kompose.image-pull-policy: 'Always'

  service-role:
    build:
      context: .
      dockerfile: apps/service-role/Dockerfile
      args:
        NODE_ENV: development
    image: 'service-role:latest'
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50052:50052
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: 'gitlabregcrednew'
      kompose.image-pull-policy: 'Always'

  service-tenant:
    build:
      context: .
      dockerfile: apps/service-tenant/Dockerfile
      args:
        NODE_ENV: development
    image: 'service-tenant:latest'
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50053:50053
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: 'gitlabregcrednew'
      kompose.image-pull-policy: 'Always'

  service-webhook:
    build:
      context: .
      dockerfile: apps/service-webhook/Dockerfile
      args:
        NODE_ENV: development
    image: 'service-webhook:latest'
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50049:50049
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: 'gitlabregcrednew'
      kompose.image-pull-policy: 'Always'

  api-admin:
    build:
      context: .
      dockerfile: apps/api-admin/Dockerfile
      args:
        NODE_ENV: development
    image: 'api-admin:latest'
    restart: always
    depends_on:
      - consul
      - redis
    environment:
      - CONSUL_HOST=consul
      - NATS_HOST=nats
      - REDIS_HOST=nats
      - DISCOVERY_HOST=localhost
    ports:
      - 50020:50020
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: 'true'
      kompose.image-pull-secret: 'gitlabregcrednew'
      kompose.image-pull-policy: 'Always'

  consul:
    container_name: consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8302:8302'
      - '8600:53/udp'
      - '8500:8500'
    image: consul
    command: ['agent', '-server', '-bootstrap', '-ui', '-client', '0.0.0.0']
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: 'true'
      kompose.image-pull-policy: 'Always'

  eventstore:
    container_name: eventstore
    ports:
      - '2113:2113'
      - '1113:1113'
    image: eventstore/eventstore:release-5.0.8
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: 'true'
      kompose.image-pull-policy: 'Always'

  nats:
    container_name: nats
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    image: nats
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: 'true'
      kompose.image-pull-policy: 'Always'

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeit
    restart: always
    expose:
      - 27017

  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - 6379
